#include "backend/codegen/internal.h"

#include "frontend/schema.h"
#include "util/strbuf.h"

#include <assert.h>
#include <stddef.h>
#include <stdlib.h>

static void emit_derived_fns(const Gen *g, const Type *t, bool is_root) {
  switch (t->kind) {
  case TypeKind_OPTIONAL:
    emit_derived_fns(g, t->optional.inner, false);
    break;
  case TypeKind_LIST:
    emit_derived_fns(g, t->list.elem, false);
    break;
  case TypeKind_MAP:
    emit_derived_fns(g, t->map.key, false);
    emit_derived_fns(g, t->map.value, false);
    break;
  case TypeKind_ENUM:
    if (!is_root) {
      codegen_emit_read_fn(g, t, codegen_name_of(g, t), false);
      codegen_emit_write_fn(g, t, codegen_name_of(g, t), false);
    }
    break;
  case TypeKind_STRUCT:
    for (size_t i = 0; i < t->struct_fields.len; i++) {
      emit_derived_fns(g, t->struct_fields.ptr[i].type, false);
    }
    break;
  case TypeKind_UNION:
    for (size_t i = 0; i < t->union_members.len; i++) {
      emit_derived_fns(g, t->union_members.ptr[i].type, false);
    }
    if (!is_root) {
      codegen_emit_read_fn(g, t, codegen_name_of(g, t), false);
      codegen_emit_write_fn(g, t, codegen_name_of(g, t), false);
      codegen_emit_equal_fn(g, t, codegen_name_of(g, t), false);
      codegen_emit_skip_fn(g, t, codegen_name_of(g, t), false);
      codegen_emit_size_fn(g, t, codegen_name_of(g, t), false);
    }
    break;
  default:
    break;
  }
}

static void emit_decode_fn(const Gen *g, const char *cname) {
  StrBuf *out = g->out;
  char *fn_decode = codegen_type_fn_name(g, cname, "decode");
  char *fn_read = codegen_type_fn_name(g, cname, "read");
  strbuf_appendf(out, "BareStatus %s(%s *out, const uint8_t buf[], size_t len) {\n", fn_decode,
                 cname);
  strbuf_append(out, "  BareReader r = bare_reader_new(buf, len);\n");
  strbuf_appendf(out, "  BARE_TRY(%s(&r, out));\n", fn_read);
  strbuf_append(out, "  if (bare_reader_remaining(&r) != 0) {\n"
                     "    return BareStatus_TRAILING_DATA;\n"
                     "  }\n"
                     "  return BareStatus_OK;\n"
                     "}\n\n");
  free(fn_decode);
  free(fn_read);
}

static void emit_encode_fn(const Gen *g, const char *cname) {
  StrBuf *out = g->out;
  char *fn_encode = codegen_type_fn_name(g, cname, "encode");
  char *fn_write = codegen_type_fn_name(g, cname, "write");
  strbuf_appendf(out,
                 "BareStatus %s(const %s *value, uint8_t buf[], size_t cap, size_t "
                 "*written) {\n",
                 fn_encode, cname);
  strbuf_append(out, "  BareWriter w = bare_writer_new(buf, cap);\n");
  strbuf_appendf(out, "  BARE_TRY(%s(&w, value));\n", fn_write);
  strbuf_append(out, "  *written = w.len;\n  return BareStatus_OK;\n}\n\n");
  free(fn_encode);
  free(fn_write);
}

static void emit_enum_name_fn(const Gen *g, const Type *t, const char *cname) {
  StrBuf *out = g->out;
  char *fn_name = codegen_type_fn_name(g, cname, "name");
  strbuf_appendf(out, "const char *%s(%s value) {\n", fn_name, cname);
  strbuf_append(out, "  switch (value) {\n");
  for (size_t i = 0; i < t->enum_values.len; i++) {
    const EnumValue *v = &t->enum_values.ptr[i];
    char *variant = codegen_render_variant(g, cname, v->name);
    strbuf_appendf(out, "  case %s:\n    return \"%.*s\";\n", variant, (int)v->name.len,
                   v->name.data);
    free(variant);
  }
  strbuf_append(out, "  }\n  return NULL;\n}\n\n");
  free(fn_name);
}

void codegen_emit_source_content(const Gen *g, char *const root_names[], const char *basename) {
  assert(root_names != nullptr);
  StrBuf *out = g->out;
  strbuf_appendf(out, "// Generated by barec %s from %s.bare, do not edit.\n", BAREC_VERSION,
                 basename);
  strbuf_appendf(out, "#include \"%s.h\"\n\n#include \"bare.h\"\n\n", basename);
  strbuf_append(out, "#include <stddef.h>\n#include <stdint.h>\n#include <string.h>\n\n");
  for (size_t i = 0; i < g->schema->len; i++) {
    if (root_names[i] == nullptr) {
      continue;
    }
    const UserType *ut = &g->schema->ptr[i];
    emit_derived_fns(g, ut->type, true);
    codegen_emit_read_fn(g, ut->type, root_names[i], true);
    codegen_emit_write_fn(g, ut->type, root_names[i], true);
    emit_decode_fn(g, root_names[i]);
    emit_encode_fn(g, root_names[i]);
    codegen_emit_equal_fn(g, ut->type, root_names[i], true);
    codegen_emit_skip_fn(g, ut->type, root_names[i], true);
    codegen_emit_size_fn(g, ut->type, root_names[i], true);
    if (ut->type->kind == TypeKind_ENUM) {
      emit_enum_name_fn(g, ut->type, root_names[i]);
    }
  }
  if (out->len >= 2 && out->data[out->len - 1] == '\n' && out->data[out->len - 2] == '\n') {
    out->len -= 1;
    out->data[out->len] = '\0';
  }
}
