#include "backend/codegen.h"

#include "backend/codegen/internal.h"
#include "backend/config.h"
#include "backend/names.h"
#include "frontend/schema.h"
#include "util/diag.h"
#include "util/macros.h"
#include "util/strbuf.h"
#include "util/types.h"
#include "util/vec.h"

#include <assert.h>
#include <inttypes.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

static void emit_hash_define(const Gen *g, const UserType *t, const char *cname) {
  StrBuf name = {};
  Str base = {.data = cname, .len = codegen_type_base_len(g->cfg, cname)};
  name_render(base, CaseStyle_SCREAMING, &name);
  strbuf_append(&name, "_SCHEMA_HASH");
  strbuf_appendf(g->out, "#define %s UINT64_C(0x%016" PRIx64 ")\n\n", name.data, type_wire_hash(t));
  strbuf_free(&name);
}

static void emit_function_decls(Gen *g, const char *cname) {
  StrBuf *out = g->out;
  const char *nd = g->cfg->std == CStd_C23 ? "[[nodiscard]]" : "BARE_NODISCARD";
  char *fn_read = codegen_type_fn_name(g, cname, "read");
  char *fn_write = codegen_type_fn_name(g, cname, "write");
  char *fn_decode = codegen_type_fn_name(g, cname, "decode");
  char *fn_encode = codegen_type_fn_name(g, cname, "encode");
  strbuf_appendf(out, "%s BareStatus %s(BareReader *r, %s *out);\n", nd, fn_read, cname);
  strbuf_appendf(out, "%s BareStatus %s(BareWriter *w, const %s *value);\n", nd, fn_write, cname);
  strbuf_appendf(out, "%s BareStatus %s(%s *out, const uint8_t buf[], size_t len);\n", nd,
                 fn_decode, cname);
  strbuf_appendf(out,
                 "%s BareStatus %s(const %s *value, uint8_t buf[], size_t cap, size_t "
                 "*written);\n",
                 nd, fn_encode, cname);
  char *fn_equal = codegen_type_fn_name(g, cname, "equal");
  strbuf_appendf(out, "%s bool %s(const %s *a, const %s *b);\n", nd, fn_equal, cname, cname);
  free(fn_equal);
  char *fn_skip = codegen_type_fn_name(g, cname, "skip");
  strbuf_appendf(out, "%s BareStatus %s(BareReader *r);\n", nd, fn_skip);
  free(fn_skip);
  free(fn_read);
  free(fn_write);
  free(fn_decode);
  free(fn_encode);
}

[[nodiscard]] static bool check_name_collisions(Gen *g, char *const root_names[]) {
  assert(root_names != nullptr);
  VEC(GenNameView) all = {};
  for (size_t i = 0; i < g->schema->len; i++) {
    TypeKind kind = g->schema->ptr[i].type->kind;
    if (root_names[i] != nullptr && kind != TypeKind_ENUM && kind != TypeKind_UNION) {
      VEC_PUSH(&all, root_names[i]);
    }
  }
  for (size_t i = 0; i < g->names.len; i++) {
    VEC_PUSH(&all, g->names.ptr[i].name);
  }
  for (size_t i = 0; i < g->tag_names.len; i++) {
    VEC_PUSH(&all, g->tag_names.ptr[i].name);
  }
  StrBuf shared = {};
  for (size_t i = 0; i < g->str_caps.len; i++) {
    strbuf_appendf(&shared, "\nBareStr%" PRIu32 "\n", g->str_caps.ptr[i]);
  }
  for (size_t i = 0; i < g->data_caps.len; i++) {
    strbuf_appendf(&shared, "\nBareData%" PRIu32 "\n", g->data_caps.ptr[i]);
  }
  bool ok = true;
  for (size_t i = 0; i < all.len && ok; i++) {
    for (size_t j = 0; j < i && ok; j++) {
      if (strcmp(all.ptr[i], all.ptr[j]) == 0) {
        diag_set_global(g->diag, "generated type name '%s' is used more than once", all.ptr[i]);
        ok = false;
      }
    }
    if (ok && shared.data != nullptr) {
      StrBuf line = {};
      strbuf_appendf(&line, "\n%s\n", all.ptr[i]);
      if (strstr(shared.data, line.data) != nullptr) {
        diag_set_global(g->diag, "generated type name '%s' collides with a shared typedef",
                        all.ptr[i]);
        ok = false;
      }
      strbuf_free(&line);
    }
  }
  strbuf_free(&shared);
  free((void *)all.ptr);
  return ok;
}

static void emit_header_content(Gen *g, char *const root_names[], const char *basename) {
  assert(root_names != nullptr);
  StrBuf *out = g->out;
  strbuf_appendf(out, "// Generated by barec from %s.bare, do not edit.\n", basename);
  strbuf_append(out, "#pragma once\n\n#include \"bare.h\"\n\n");
  if (g->cfg->std == CStd_C99) {
    strbuf_append(out, "#include <stdbool.h>\n");
  }
  strbuf_append(out, "#include <stddef.h>\n#include <stdint.h>\n\n");
  codegen_emit_shared_typedefs(g);
  for (size_t i = 0; i < g->schema->len; i++) {
    if (root_names[i] == nullptr) {
      continue;
    }
    codegen_emit_derived_defs(g, g->schema->ptr[i].type, true);
    codegen_emit_root_def(g, &g->schema->ptr[i], root_names[i]);
    codegen_emit_size_define(g, g->schema->ptr[i].type, root_names[i]);
    emit_hash_define(g, &g->schema->ptr[i], root_names[i]);
  }
  bool first = true;
  for (size_t i = 0; i < g->schema->len; i++) {
    if (root_names[i] == nullptr) {
      continue;
    }
    if (!first) {
      strbuf_append(out, "\n");
    }
    emit_function_decls(g, root_names[i]);
    if (g->schema->ptr[i].type->kind == TypeKind_ENUM) {
      char *fn_name = codegen_type_fn_name(g, root_names[i], "name");
      strbuf_appendf(out, "const char *%s(%s value);\n", fn_name, root_names[i]);
      free(fn_name);
    }
    first = false;
  }
}

[[nodiscard]] static bool check_overrides_used(const Gen *g) {
  for (size_t i = 0; i < g->cfg->overrides.len; i++) {
    if (!g->override_used[i]) {
      diag_set_global(g->diag, "cap override '%.*s' does not match any schema element",
                      (int)g->cfg->overrides.ptr[i].path.len, g->cfg->overrides.ptr[i].path.data);
      return false;
    }
  }
  return true;
}

static void gen_free(Gen *g, char *root_names[]) {
  for (size_t i = 0; i < g->schema->len; i++) {
    free(root_names[i]);
  }
  free((void *)root_names);
  for (size_t i = 0; i < g->names.len; i++) {
    free(g->names.ptr[i].name);
  }
  free(g->names.ptr);
  for (size_t i = 0; i < g->tag_names.len; i++) {
    free(g->tag_names.ptr[i].name);
  }
  free(g->tag_names.ptr);
  for (size_t i = 0; i < g->union_bases.len; i++) {
    VEC(GenName) *bases = &g->union_bases.ptr[i].bases;
    for (size_t j = 0; j < bases->len; j++) {
      free(bases->ptr[j]);
    }
    free((void *)bases->ptr);
  }
  free(g->union_bases.ptr);
  free(g->caps.ptr);
  free(g->str_caps.ptr);
  free(g->data_caps.ptr);
  free(g->override_used);
  free(g->members.has_value);
  free(g->members.value);
  free(g->members.items);
  free(g->members.len);
  free(g->members.entries);
  free(g->members.key);
  free(g->members.tag);
  free(g->members.data);
}

bool codegen_generate(const Schema *schema, const Config *cfg, const char *basename, StrBuf *header,
                      StrBuf *source, Diag *diag) {
  assert(schema->len > 0);
  Gen g = {.schema = schema, .cfg = cfg, .diag = diag, .out = header};
  g.override_used = calloc(MAX(cfg->overrides.len, (size_t)1), sizeof(bool));
  if (g.override_used == nullptr) {
    abort();
  }
  g.members.has_value = codegen_render_ident_cstr(cfg, "has_value", cfg->field_case, false);
  g.members.value = codegen_render_ident_cstr(cfg, "value", cfg->field_case, false);
  g.members.items = codegen_render_ident_cstr(cfg, "items", cfg->field_case, false);
  g.members.len = codegen_render_ident_cstr(cfg, "len", cfg->field_case, false);
  g.members.entries = codegen_render_ident_cstr(cfg, "entries", cfg->field_case, false);
  g.members.key = codegen_render_ident_cstr(cfg, "key", cfg->field_case, false);
  g.members.tag = codegen_render_ident_cstr(cfg, "tag", cfg->field_case, false);
  g.members.data = codegen_render_ident_cstr(cfg, "data", cfg->field_case, false);
  StrBuf path = {};
  for (size_t i = 0; i < schema->len; i++) {
    path.len = 0;
    if (path.data != nullptr) {
      path.data[0] = '\0';
    }
    strbuf_append_str(&path, schema->ptr[i].name);
    codegen_scan_type(&g, schema->ptr[i].type, &path);
  }
  strbuf_free(&path);

  char **root_names = (char **)calloc(schema->len, sizeof(char *));
  if (root_names == nullptr) {
    abort();
  }
  for (size_t i = 0; i < schema->len; i++) {
    if (type_underlying(schema->ptr[i].type)->kind != TypeKind_VOID) {
      root_names[i] = codegen_render_type_name(cfg, schema->ptr[i].name);
    }
  }

  bool ok = check_overrides_used(&g);
  if (ok) {
    ok = check_name_collisions(&g, root_names);
  }
  if (ok) {
    emit_header_content(&g, root_names, basename);
    g.out = source;
    codegen_emit_source_content(&g, root_names, basename);
  }
  gen_free(&g, root_names);
  return ok;
}
