// Generated by barec from example_default.bare, do not edit.
#pragma once

#include "bare.h"

#include <stddef.h>
#include <stdint.h>

#ifndef BARE_STR64_DEFINED
#define BARE_STR64_DEFINED
typedef struct {
  char data[64] BARE_NONSTRING;
  uint32_t len;
} BareStr64;
#define BARE_STR64(lit) ((BareStr64){.data = "" lit, .len = sizeof(lit) - 1})
#endif

#ifndef BARE_DATA64_DEFINED
#define BARE_DATA64_DEFINED
typedef struct {
  uint8_t data[64];
  uint32_t len;
} BareData64;
#endif

typedef struct {
  uint8_t data[128];
} PublicKey;

#define PUBLIC_KEY_SIZE 128

typedef BareStr64 Time;

#define TIME_MAX_SIZE 65

typedef enum : uint8_t {
  Department_ACCOUNTING = 0,
  Department_ADMINISTRATION = 1,
  Department_CUSTOMER_SERVICE = 2,
  Department_DEVELOPMENT = 3,
  Department_JSMITH = 99,
} Department;

#define DEPARTMENT_SIZE 1

typedef struct {
  BareStr64 items[4];
} Address;

#define ADDRESS_MAX_SIZE 260

typedef struct {
  BareStr64 name;
  BareStr64 email;
  Address address;
  struct {
    struct {
      int64_t order_id;
      int32_t quantity;
    } items[8];
    uint32_t len;
  } orders;
  struct {
    struct {
      BareStr64 key;
      BareData64 value;
    } entries[8];
    uint32_t len;
  } metadata;
} Customer;

#define CUSTOMER_MAX_SIZE 1528

typedef struct {
  BareStr64 name;
  BareStr64 email;
  Address address;
  Department department;
  Time hire_date;
  struct {
    bool has_value;
    PublicKey value;
  } public_key;
  struct {
    struct {
      BareStr64 key;
      BareData64 value;
    } entries[8];
    uint32_t len;
  } metadata;
} Employee;

#define EMPLOYEE_MAX_SIZE 1626

typedef enum : uint8_t {
  PersonTag_CUSTOMER = 0,
  PersonTag_EMPLOYEE = 1,
  PersonTag_TERMINATED_EMPLOYEE = 2,
} PersonTag;

typedef struct {
  PersonTag tag;
  union {
    Customer customer;
    Employee employee;
  } value;
} Person;

#define PERSON_MAX_SIZE 1627

[[nodiscard]] BareStatus public_key_read(BareReader *r, PublicKey *out);
[[nodiscard]] BareStatus public_key_write(BareWriter *w, const PublicKey *value);
[[nodiscard]] BareStatus public_key_decode(PublicKey *out, const uint8_t buf[], size_t len);
[[nodiscard]] BareStatus public_key_encode(const PublicKey *value, uint8_t buf[], size_t cap, size_t *written);

[[nodiscard]] BareStatus time_read(BareReader *r, Time *out);
[[nodiscard]] BareStatus time_write(BareWriter *w, const Time *value);
[[nodiscard]] BareStatus time_decode(Time *out, const uint8_t buf[], size_t len);
[[nodiscard]] BareStatus time_encode(const Time *value, uint8_t buf[], size_t cap, size_t *written);

[[nodiscard]] BareStatus department_read(BareReader *r, Department *out);
[[nodiscard]] BareStatus department_write(BareWriter *w, const Department *value);
[[nodiscard]] BareStatus department_decode(Department *out, const uint8_t buf[], size_t len);
[[nodiscard]] BareStatus department_encode(const Department *value, uint8_t buf[], size_t cap, size_t *written);

[[nodiscard]] BareStatus address_read(BareReader *r, Address *out);
[[nodiscard]] BareStatus address_write(BareWriter *w, const Address *value);
[[nodiscard]] BareStatus address_decode(Address *out, const uint8_t buf[], size_t len);
[[nodiscard]] BareStatus address_encode(const Address *value, uint8_t buf[], size_t cap, size_t *written);

[[nodiscard]] BareStatus customer_read(BareReader *r, Customer *out);
[[nodiscard]] BareStatus customer_write(BareWriter *w, const Customer *value);
[[nodiscard]] BareStatus customer_decode(Customer *out, const uint8_t buf[], size_t len);
[[nodiscard]] BareStatus customer_encode(const Customer *value, uint8_t buf[], size_t cap, size_t *written);

[[nodiscard]] BareStatus employee_read(BareReader *r, Employee *out);
[[nodiscard]] BareStatus employee_write(BareWriter *w, const Employee *value);
[[nodiscard]] BareStatus employee_decode(Employee *out, const uint8_t buf[], size_t len);
[[nodiscard]] BareStatus employee_encode(const Employee *value, uint8_t buf[], size_t cap, size_t *written);

[[nodiscard]] BareStatus person_read(BareReader *r, Person *out);
[[nodiscard]] BareStatus person_write(BareWriter *w, const Person *value);
[[nodiscard]] BareStatus person_decode(Person *out, const uint8_t buf[], size_t len);
[[nodiscard]] BareStatus person_encode(const Person *value, uint8_t buf[], size_t cap, size_t *written);
