// Generated by barec from example_default.bare, do not edit.
#include "example_default.h"

#include "bare.h"

#include <stddef.h>
#include <stdint.h>
#include <string.h>

BareStatus public_key_read(BareReader *r, PublicKey *out) {
  return bare_read_data_fixed(r, out->data, 128);
}

BareStatus public_key_write(BareWriter *w, const PublicKey *value) {
  return bare_write_data_fixed(w, value->data, 128);
}

BareStatus public_key_decode(PublicKey *out, const uint8_t buf[], size_t len) {
  BareReader r = bare_reader_new(buf, len);
  BARE_TRY(public_key_read(&r, out));
  if (bare_reader_remaining(&r) != 0) {
    return BareStatus_TRAILING_DATA;
  }
  return BareStatus_OK;
}

BareStatus public_key_encode(const PublicKey *value, uint8_t buf[], size_t cap, size_t *written) {
  BareWriter w = bare_writer_new(buf, cap);
  BARE_TRY(public_key_write(&w, value));
  *written = w.len;
  return BareStatus_OK;
}

bool public_key_equal(const PublicKey *a, const PublicKey *b) {
  return memcmp(a->data, b->data, 128) == 0;
}

BareStatus time_read(BareReader *r, Time *out) {
  return bare_read_str(r, out->data, 64, &out->len);
}

BareStatus time_write(BareWriter *w, const Time *value) {
  if (value->len > 64) {
    return BareStatus_CAP_EXCEEDED;
  }
  return bare_write_str(w, value->data, value->len);
}

BareStatus time_decode(Time *out, const uint8_t buf[], size_t len) {
  BareReader r = bare_reader_new(buf, len);
  BARE_TRY(time_read(&r, out));
  if (bare_reader_remaining(&r) != 0) {
    return BareStatus_TRAILING_DATA;
  }
  return BareStatus_OK;
}

BareStatus time_encode(const Time *value, uint8_t buf[], size_t cap, size_t *written) {
  BareWriter w = bare_writer_new(buf, cap);
  BARE_TRY(time_write(&w, value));
  *written = w.len;
  return BareStatus_OK;
}

bool time_equal(const Time *a, const Time *b) {
  return a->len == b->len && memcmp(a->data, b->data, a->len) == 0;
}

BareStatus department_read(BareReader *r, Department *out) {
  uint64_t raw;
  BARE_TRY(bare_read_uint(r, &raw));
  switch (raw) {
  case 0:
  case 1:
  case 2:
  case 3:
  case 99:
    break;
  default:
    return BareStatus_INVALID_ENUM;
  }
  *out = (Department)raw;
  return BareStatus_OK;
}

BareStatus department_write(BareWriter *w, const Department *value) {
  switch ((uint64_t)*value) {
  case 0:
  case 1:
  case 2:
  case 3:
  case 99:
    break;
  default:
    return BareStatus_INVALID_ENUM;
  }
  return bare_write_uint(w, (uint64_t)*value);
}

BareStatus department_decode(Department *out, const uint8_t buf[], size_t len) {
  BareReader r = bare_reader_new(buf, len);
  BARE_TRY(department_read(&r, out));
  if (bare_reader_remaining(&r) != 0) {
    return BareStatus_TRAILING_DATA;
  }
  return BareStatus_OK;
}

BareStatus department_encode(const Department *value, uint8_t buf[], size_t cap, size_t *written) {
  BareWriter w = bare_writer_new(buf, cap);
  BARE_TRY(department_write(&w, value));
  *written = w.len;
  return BareStatus_OK;
}

bool department_equal(const Department *a, const Department *b) {
  return *a == *b;
}

const char *department_name(Department value) {
  switch (value) {
  case Department_ACCOUNTING:
    return "ACCOUNTING";
  case Department_ADMINISTRATION:
    return "ADMINISTRATION";
  case Department_CUSTOMER_SERVICE:
    return "CUSTOMER_SERVICE";
  case Department_DEVELOPMENT:
    return "DEVELOPMENT";
  case Department_JSMITH:
    return "JSMITH";
  }
  return NULL;
}

BareStatus address_read(BareReader *r, Address *out) {
  for (uint64_t i0 = 0; i0 < 4; i0++) {
    BARE_TRY(bare_read_str(r, out->items[i0].data, 64, &out->items[i0].len));
  }
  return BareStatus_OK;
}

BareStatus address_write(BareWriter *w, const Address *value) {
  for (uint64_t i0 = 0; i0 < 4; i0++) {
    if (value->items[i0].len > 64) {
      return BareStatus_CAP_EXCEEDED;
    }
    BARE_TRY(bare_write_str(w, value->items[i0].data, value->items[i0].len));
  }
  return BareStatus_OK;
}

BareStatus address_decode(Address *out, const uint8_t buf[], size_t len) {
  BareReader r = bare_reader_new(buf, len);
  BARE_TRY(address_read(&r, out));
  if (bare_reader_remaining(&r) != 0) {
    return BareStatus_TRAILING_DATA;
  }
  return BareStatus_OK;
}

BareStatus address_encode(const Address *value, uint8_t buf[], size_t cap, size_t *written) {
  BareWriter w = bare_writer_new(buf, cap);
  BARE_TRY(address_write(&w, value));
  *written = w.len;
  return BareStatus_OK;
}

bool address_equal(const Address *a, const Address *b) {
  for (uint64_t i0 = 0; i0 < 4; i0++) {
    if (a->items[i0].len != b->items[i0].len || memcmp(a->items[i0].data, b->items[i0].data, a->items[i0].len) != 0) {
      return false;
    }
  }
  return true;
}

BareStatus customer_read(BareReader *r, Customer *out) {
  BARE_TRY(bare_read_str(r, out->name.data, 64, &out->name.len));
  BARE_TRY(bare_read_str(r, out->email.data, 64, &out->email.len));
  BARE_TRY(address_read(r, &out->address));
  {
    uint64_t n0;
    BARE_TRY(bare_read_uint(r, &n0));
    if (n0 > 8) {
      return BareStatus_CAP_EXCEEDED;
    }
    out->orders.len = (uint32_t)n0;
    for (uint32_t i0 = 0; i0 < out->orders.len; i0++) {
      BARE_TRY(bare_read_i64(r, &out->orders.items[i0].order_id));
      BARE_TRY(bare_read_i32(r, &out->orders.items[i0].quantity));
    }
  }
  {
    uint64_t n0;
    BARE_TRY(bare_read_uint(r, &n0));
    if (n0 > 8) {
      return BareStatus_CAP_EXCEEDED;
    }
    out->metadata.len = (uint32_t)n0;
    for (uint32_t i0 = 0; i0 < out->metadata.len; i0++) {
      BARE_TRY(bare_read_str(r, out->metadata.entries[i0].key.data, 64, &out->metadata.entries[i0].key.len));
      BARE_TRY(bare_read_data(r, out->metadata.entries[i0].value.data, 64, &out->metadata.entries[i0].value.len));
      for (uint32_t j0 = 0; j0 < i0; j0++) {
        if (out->metadata.entries[j0].key.len == out->metadata.entries[i0].key.len && memcmp(out->metadata.entries[j0].key.data, out->metadata.entries[i0].key.data, out->metadata.entries[j0].key.len) == 0) {
          return BareStatus_DUPLICATE_KEY;
        }
      }
    }
  }
  return BareStatus_OK;
}

BareStatus customer_write(BareWriter *w, const Customer *value) {
  if (value->name.len > 64) {
    return BareStatus_CAP_EXCEEDED;
  }
  BARE_TRY(bare_write_str(w, value->name.data, value->name.len));
  if (value->email.len > 64) {
    return BareStatus_CAP_EXCEEDED;
  }
  BARE_TRY(bare_write_str(w, value->email.data, value->email.len));
  BARE_TRY(address_write(w, &value->address));
  if (value->orders.len > 8) {
    return BareStatus_CAP_EXCEEDED;
  }
  BARE_TRY(bare_write_uint(w, value->orders.len));
  for (uint32_t i0 = 0; i0 < value->orders.len; i0++) {
    BARE_TRY(bare_write_i64(w, value->orders.items[i0].order_id));
    BARE_TRY(bare_write_i32(w, value->orders.items[i0].quantity));
  }
  if (value->metadata.len > 8) {
    return BareStatus_CAP_EXCEEDED;
  }
  BARE_TRY(bare_write_uint(w, value->metadata.len));
  for (uint32_t i0 = 0; i0 < value->metadata.len; i0++) {
    if (value->metadata.entries[i0].key.len > 64) {
      return BareStatus_CAP_EXCEEDED;
    }
    BARE_TRY(bare_write_str(w, value->metadata.entries[i0].key.data, value->metadata.entries[i0].key.len));
    if (value->metadata.entries[i0].value.len > 64) {
      return BareStatus_CAP_EXCEEDED;
    }
    BARE_TRY(bare_write_data(w, value->metadata.entries[i0].value.data, value->metadata.entries[i0].value.len));
  }
  return BareStatus_OK;
}

BareStatus customer_decode(Customer *out, const uint8_t buf[], size_t len) {
  BareReader r = bare_reader_new(buf, len);
  BARE_TRY(customer_read(&r, out));
  if (bare_reader_remaining(&r) != 0) {
    return BareStatus_TRAILING_DATA;
  }
  return BareStatus_OK;
}

BareStatus customer_encode(const Customer *value, uint8_t buf[], size_t cap, size_t *written) {
  BareWriter w = bare_writer_new(buf, cap);
  BARE_TRY(customer_write(&w, value));
  *written = w.len;
  return BareStatus_OK;
}

bool customer_equal(const Customer *a, const Customer *b) {
  if (a->name.len != b->name.len || memcmp(a->name.data, b->name.data, a->name.len) != 0) {
    return false;
  }
  if (a->email.len != b->email.len || memcmp(a->email.data, b->email.data, a->email.len) != 0) {
    return false;
  }
  if (!address_equal(&a->address, &b->address)) {
    return false;
  }
  if (a->orders.len != b->orders.len) {
    return false;
  }
  for (uint64_t i0 = 0; i0 < a->orders.len; i0++) {
    if (a->orders.items[i0].order_id != b->orders.items[i0].order_id) {
      return false;
    }
    if (a->orders.items[i0].quantity != b->orders.items[i0].quantity) {
      return false;
    }
  }
  if (a->metadata.len != b->metadata.len) {
    return false;
  }
  for (uint64_t i0 = 0; i0 < a->metadata.len; i0++) {
    if (a->metadata.entries[i0].key.len != b->metadata.entries[i0].key.len || memcmp(a->metadata.entries[i0].key.data, b->metadata.entries[i0].key.data, a->metadata.entries[i0].key.len) != 0) {
      return false;
    }
    if (a->metadata.entries[i0].value.len != b->metadata.entries[i0].value.len || memcmp(a->metadata.entries[i0].value.data, b->metadata.entries[i0].value.data, a->metadata.entries[i0].value.len) != 0) {
      return false;
    }
  }
  return true;
}

BareStatus employee_read(BareReader *r, Employee *out) {
  BARE_TRY(bare_read_str(r, out->name.data, 64, &out->name.len));
  BARE_TRY(bare_read_str(r, out->email.data, 64, &out->email.len));
  BARE_TRY(address_read(r, &out->address));
  BARE_TRY(department_read(r, &out->department));
  BARE_TRY(time_read(r, &out->hire_date));
  {
    uint8_t p0;
    BARE_TRY(bare_read_u8(r, &p0));
    if (p0 > 1) {
      return BareStatus_INVALID_OPTIONAL;
    }
    out->public_key.has_value = p0 == 1;
    if (out->public_key.has_value) {
      BARE_TRY(public_key_read(r, &out->public_key.value));
    }
  }
  {
    uint64_t n0;
    BARE_TRY(bare_read_uint(r, &n0));
    if (n0 > 8) {
      return BareStatus_CAP_EXCEEDED;
    }
    out->metadata.len = (uint32_t)n0;
    for (uint32_t i0 = 0; i0 < out->metadata.len; i0++) {
      BARE_TRY(bare_read_str(r, out->metadata.entries[i0].key.data, 64, &out->metadata.entries[i0].key.len));
      BARE_TRY(bare_read_data(r, out->metadata.entries[i0].value.data, 64, &out->metadata.entries[i0].value.len));
      for (uint32_t j0 = 0; j0 < i0; j0++) {
        if (out->metadata.entries[j0].key.len == out->metadata.entries[i0].key.len && memcmp(out->metadata.entries[j0].key.data, out->metadata.entries[i0].key.data, out->metadata.entries[j0].key.len) == 0) {
          return BareStatus_DUPLICATE_KEY;
        }
      }
    }
  }
  return BareStatus_OK;
}

BareStatus employee_write(BareWriter *w, const Employee *value) {
  if (value->name.len > 64) {
    return BareStatus_CAP_EXCEEDED;
  }
  BARE_TRY(bare_write_str(w, value->name.data, value->name.len));
  if (value->email.len > 64) {
    return BareStatus_CAP_EXCEEDED;
  }
  BARE_TRY(bare_write_str(w, value->email.data, value->email.len));
  BARE_TRY(address_write(w, &value->address));
  BARE_TRY(department_write(w, &value->department));
  BARE_TRY(time_write(w, &value->hire_date));
  BARE_TRY(bare_write_u8(w, (uint8_t)value->public_key.has_value));
  if (value->public_key.has_value) {
    BARE_TRY(public_key_write(w, &value->public_key.value));
  }
  if (value->metadata.len > 8) {
    return BareStatus_CAP_EXCEEDED;
  }
  BARE_TRY(bare_write_uint(w, value->metadata.len));
  for (uint32_t i0 = 0; i0 < value->metadata.len; i0++) {
    if (value->metadata.entries[i0].key.len > 64) {
      return BareStatus_CAP_EXCEEDED;
    }
    BARE_TRY(bare_write_str(w, value->metadata.entries[i0].key.data, value->metadata.entries[i0].key.len));
    if (value->metadata.entries[i0].value.len > 64) {
      return BareStatus_CAP_EXCEEDED;
    }
    BARE_TRY(bare_write_data(w, value->metadata.entries[i0].value.data, value->metadata.entries[i0].value.len));
  }
  return BareStatus_OK;
}

BareStatus employee_decode(Employee *out, const uint8_t buf[], size_t len) {
  BareReader r = bare_reader_new(buf, len);
  BARE_TRY(employee_read(&r, out));
  if (bare_reader_remaining(&r) != 0) {
    return BareStatus_TRAILING_DATA;
  }
  return BareStatus_OK;
}

BareStatus employee_encode(const Employee *value, uint8_t buf[], size_t cap, size_t *written) {
  BareWriter w = bare_writer_new(buf, cap);
  BARE_TRY(employee_write(&w, value));
  *written = w.len;
  return BareStatus_OK;
}

bool employee_equal(const Employee *a, const Employee *b) {
  if (a->name.len != b->name.len || memcmp(a->name.data, b->name.data, a->name.len) != 0) {
    return false;
  }
  if (a->email.len != b->email.len || memcmp(a->email.data, b->email.data, a->email.len) != 0) {
    return false;
  }
  if (!address_equal(&a->address, &b->address)) {
    return false;
  }
  if (!department_equal(&a->department, &b->department)) {
    return false;
  }
  if (!time_equal(&a->hire_date, &b->hire_date)) {
    return false;
  }
  if (a->public_key.has_value != b->public_key.has_value) {
    return false;
  }
  if (a->public_key.has_value) {
    if (!public_key_equal(&a->public_key.value, &b->public_key.value)) {
      return false;
    }
  }
  if (a->metadata.len != b->metadata.len) {
    return false;
  }
  for (uint64_t i0 = 0; i0 < a->metadata.len; i0++) {
    if (a->metadata.entries[i0].key.len != b->metadata.entries[i0].key.len || memcmp(a->metadata.entries[i0].key.data, b->metadata.entries[i0].key.data, a->metadata.entries[i0].key.len) != 0) {
      return false;
    }
    if (a->metadata.entries[i0].value.len != b->metadata.entries[i0].value.len || memcmp(a->metadata.entries[i0].value.data, b->metadata.entries[i0].value.data, a->metadata.entries[i0].value.len) != 0) {
      return false;
    }
  }
  return true;
}

BareStatus person_read(BareReader *r, Person *out) {
  uint64_t tag;
  BARE_TRY(bare_read_uint(r, &tag));
  switch (tag) {
  case 0:
    out->tag = PersonTag_CUSTOMER;
    BARE_TRY(customer_read(r, &out->value.customer));
    break;
  case 1:
    out->tag = PersonTag_EMPLOYEE;
    BARE_TRY(employee_read(r, &out->value.employee));
    break;
  case 2:
    out->tag = PersonTag_TERMINATED_EMPLOYEE;
    break;
  default:
    return BareStatus_INVALID_TAG;
  }
  return BareStatus_OK;
}

BareStatus person_write(BareWriter *w, const Person *value) {
  switch (value->tag) {
  case PersonTag_CUSTOMER:
    BARE_TRY(bare_write_uint(w, 0));
    BARE_TRY(customer_write(w, &value->value.customer));
    break;
  case PersonTag_EMPLOYEE:
    BARE_TRY(bare_write_uint(w, 1));
    BARE_TRY(employee_write(w, &value->value.employee));
    break;
  case PersonTag_TERMINATED_EMPLOYEE:
    BARE_TRY(bare_write_uint(w, 2));
    break;
  default:
    return BareStatus_INVALID_TAG;
  }
  return BareStatus_OK;
}

BareStatus person_decode(Person *out, const uint8_t buf[], size_t len) {
  BareReader r = bare_reader_new(buf, len);
  BARE_TRY(person_read(&r, out));
  if (bare_reader_remaining(&r) != 0) {
    return BareStatus_TRAILING_DATA;
  }
  return BareStatus_OK;
}

BareStatus person_encode(const Person *value, uint8_t buf[], size_t cap, size_t *written) {
  BareWriter w = bare_writer_new(buf, cap);
  BARE_TRY(person_write(&w, value));
  *written = w.len;
  return BareStatus_OK;
}

bool person_equal(const Person *a, const Person *b) {
  if (a->tag != b->tag) {
    return false;
  }
  switch (a->tag) {
  case PersonTag_CUSTOMER:
    if (!customer_equal(&a->value.customer, &b->value.customer)) {
      return false;
    }
    break;
  case PersonTag_EMPLOYEE:
    if (!employee_equal(&a->value.employee, &b->value.employee)) {
      return false;
    }
    break;
  case PersonTag_TERMINATED_EMPLOYEE:
    break;
  }
  return true;
}
