// Generated by barec 0.2.0 from showcase.bare, do not edit.
#pragma once

#include "bare.h"

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#ifndef BARE_STR64_DEFINED
#define BARE_STR64_DEFINED
typedef struct {
  char data[64] BARE_NONSTRING;
  uint32_t len;
} BareStr64;
#define BARE_STR64(lit) ((BareStr64){.data = "" lit, .len = (sizeof(struct { int bare_string_literal_longer_than_capacity : sizeof(lit) - 1 <= 64 ? 1 : -1; }) * 0) + sizeof(lit) - 1})
#endif

#ifndef BARE_DATA64_DEFINED
#define BARE_DATA64_DEFINED
typedef struct {
  uint8_t data[64];
  uint32_t len;
} BareData64;
#endif

typedef uint64_t UserId;

#define USER_ID_SIZE 8

#define USER_ID_SCHEMA_HASH UINT64_C(0x0f25b8a696d73eea)

typedef uint8_t Color;
enum {
  Color_RED = 0,
  Color_GREEN = 1,
  Color_BLUE = 10,
};

#define COLOR_SIZE 1

#define COLOR_SCHEMA_HASH UINT64_C(0xa4d398d4719edb87)

typedef struct {
  BareStr64 display_name;
  struct {
    bool has_value;
    BareData64 value;
  } avatar;
  struct {
    Color items[8];
    uint32_t len;
  } favorites;
} Profile;

#define PROFILE_MAX_SIZE 140

#define PROFILE_SCHEMA_HASH UINT64_C(0xb4c71ea44c561a1c)

typedef struct {
  UserId user;
  uint64_t when;
} LoginEvent;

#define LOGIN_EVENT_SIZE 16

#define LOGIN_EVENT_SCHEMA_HASH UINT64_C(0x98e7798f4c4eab58)

typedef uint8_t EventTag;
enum {
  EventTag_LOGIN_EVENT = 0,
  EventTag_PROFILE = 1,
};

typedef struct {
  EventTag tag;
  union {
    LoginEvent login_event;
    Profile profile;
  } value;
} Event;

#define EVENT_MAX_SIZE 141

#define EVENT_SCHEMA_HASH UINT64_C(0xdd088848706b0f72)

BARE_NODISCARD BareStatus user_id_read(BareReader *r, UserId *out);
BARE_NODISCARD BareStatus user_id_write(BareWriter *w, const UserId *value);
BARE_NODISCARD BareStatus user_id_decode(UserId *out, const uint8_t buf[], size_t len);
BARE_NODISCARD BareStatus user_id_encode(const UserId *value, uint8_t buf[], size_t cap, size_t *written);
BARE_NODISCARD bool user_id_equal(const UserId *a, const UserId *b);
BARE_NODISCARD BareStatus user_id_skip(BareReader *r);
BARE_NODISCARD uint64_t user_id_size(const UserId *value);

BARE_NODISCARD BareStatus color_read(BareReader *r, Color *out);
BARE_NODISCARD BareStatus color_write(BareWriter *w, const Color *value);
BARE_NODISCARD BareStatus color_decode(Color *out, const uint8_t buf[], size_t len);
BARE_NODISCARD BareStatus color_encode(const Color *value, uint8_t buf[], size_t cap, size_t *written);
BARE_NODISCARD bool color_equal(const Color *a, const Color *b);
BARE_NODISCARD BareStatus color_skip(BareReader *r);
BARE_NODISCARD uint64_t color_size(const Color *value);
const char *color_name(Color value);

BARE_NODISCARD BareStatus profile_read(BareReader *r, Profile *out);
BARE_NODISCARD BareStatus profile_write(BareWriter *w, const Profile *value);
BARE_NODISCARD BareStatus profile_decode(Profile *out, const uint8_t buf[], size_t len);
BARE_NODISCARD BareStatus profile_encode(const Profile *value, uint8_t buf[], size_t cap, size_t *written);
BARE_NODISCARD bool profile_equal(const Profile *a, const Profile *b);
BARE_NODISCARD BareStatus profile_skip(BareReader *r);
BARE_NODISCARD uint64_t profile_size(const Profile *value);

BARE_NODISCARD BareStatus login_event_read(BareReader *r, LoginEvent *out);
BARE_NODISCARD BareStatus login_event_write(BareWriter *w, const LoginEvent *value);
BARE_NODISCARD BareStatus login_event_decode(LoginEvent *out, const uint8_t buf[], size_t len);
BARE_NODISCARD BareStatus login_event_encode(const LoginEvent *value, uint8_t buf[], size_t cap, size_t *written);
BARE_NODISCARD bool login_event_equal(const LoginEvent *a, const LoginEvent *b);
BARE_NODISCARD BareStatus login_event_skip(BareReader *r);
BARE_NODISCARD uint64_t login_event_size(const LoginEvent *value);

BARE_NODISCARD BareStatus event_read(BareReader *r, Event *out);
BARE_NODISCARD BareStatus event_write(BareWriter *w, const Event *value);
BARE_NODISCARD BareStatus event_decode(Event *out, const uint8_t buf[], size_t len);
BARE_NODISCARD BareStatus event_encode(const Event *value, uint8_t buf[], size_t cap, size_t *written);
BARE_NODISCARD bool event_equal(const Event *a, const Event *b);
BARE_NODISCARD BareStatus event_skip(BareReader *r);
BARE_NODISCARD uint64_t event_size(const Event *value);
