// Generated by barec from showcase.bare, do not edit.
#pragma once

#include "bare.h"

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#ifndef BARE_STR64_DEFINED
#define BARE_STR64_DEFINED
typedef struct {
  char data[64] BARE_NONSTRING;
  uint32_t len;
} BareStr64;
#define BARE_STR64(lit) ((BareStr64){.data = "" lit, .len = sizeof(lit) - 1})
#endif

#ifndef BARE_DATA64_DEFINED
#define BARE_DATA64_DEFINED
typedef struct {
  uint8_t data[64];
  uint32_t len;
} BareData64;
#endif

typedef uint64_t UserId;

typedef uint8_t Color;
enum {
  Color_RED = 0,
  Color_GREEN = 1,
  Color_BLUE = 10,
};

typedef struct {
  BareStr64 display_name;
  struct {
    bool has_value;
    BareData64 value;
  } avatar;
  struct {
    Color items[8];
    uint32_t len;
  } favorites;
} Profile;

typedef struct {
  UserId user;
  uint64_t when;
} LoginEvent;

typedef uint8_t EventTag;
enum {
  EventTag_LOGIN_EVENT = 0,
  EventTag_PROFILE = 1,
};

typedef struct {
  EventTag tag;
  union {
    LoginEvent login_event;
    Profile profile;
  } value;
} Event;

BARE_NODISCARD BareStatus user_id_read(BareReader *r, UserId *out);
BARE_NODISCARD BareStatus user_id_write(BareWriter *w, const UserId *value);
BARE_NODISCARD BareStatus user_id_decode(UserId *out, const uint8_t buf[], size_t len);
BARE_NODISCARD BareStatus user_id_encode(const UserId *value, uint8_t buf[], size_t cap, size_t *written);

BARE_NODISCARD BareStatus color_read(BareReader *r, Color *out);
BARE_NODISCARD BareStatus color_write(BareWriter *w, const Color *value);
BARE_NODISCARD BareStatus color_decode(Color *out, const uint8_t buf[], size_t len);
BARE_NODISCARD BareStatus color_encode(const Color *value, uint8_t buf[], size_t cap, size_t *written);

BARE_NODISCARD BareStatus profile_read(BareReader *r, Profile *out);
BARE_NODISCARD BareStatus profile_write(BareWriter *w, const Profile *value);
BARE_NODISCARD BareStatus profile_decode(Profile *out, const uint8_t buf[], size_t len);
BARE_NODISCARD BareStatus profile_encode(const Profile *value, uint8_t buf[], size_t cap, size_t *written);

BARE_NODISCARD BareStatus login_event_read(BareReader *r, LoginEvent *out);
BARE_NODISCARD BareStatus login_event_write(BareWriter *w, const LoginEvent *value);
BARE_NODISCARD BareStatus login_event_decode(LoginEvent *out, const uint8_t buf[], size_t len);
BARE_NODISCARD BareStatus login_event_encode(const LoginEvent *value, uint8_t buf[], size_t cap, size_t *written);

BARE_NODISCARD BareStatus event_read(BareReader *r, Event *out);
BARE_NODISCARD BareStatus event_write(BareWriter *w, const Event *value);
BARE_NODISCARD BareStatus event_decode(Event *out, const uint8_t buf[], size_t len);
BARE_NODISCARD BareStatus event_encode(const Event *value, uint8_t buf[], size_t cap, size_t *written);
