// Generated by barec 0.2.0 from showcase.bare, do not edit.
#pragma once

#include "bare.h"

#include <stddef.h>
#include <stdint.h>

#ifndef BARE_STR64_DEFINED
#define BARE_STR64_DEFINED
typedef struct {
  char data[64] BARE_NONSTRING;
  uint32_t len;
} BareStr64;
#define BARE_STR64(lit) ((BareStr64){.data = "" lit, .len = (sizeof(struct { int bare_string_literal_longer_than_capacity : sizeof(lit) - 1 <= 64 ? 1 : -1; }) * 0) + sizeof(lit) - 1})
#endif

#ifndef BARE_DATA64_DEFINED
#define BARE_DATA64_DEFINED
typedef struct {
  uint8_t data[64];
  uint32_t len;
} BareData64;
#endif

typedef uint64_t UserId;

#define USER_ID_SIZE 8

#define USER_ID_SCHEMA_HASH UINT64_C(0x0f25b8a696d73eea)

typedef enum : uint8_t {
  Color_Red = 0,
  Color_Green = 1,
  Color_Blue = 10,
} Color;

#define COLOR_SIZE 1

#define COLOR_SCHEMA_HASH UINT64_C(0xa4d398d4719edb87)

typedef struct {
  BareStr64 displayName;
  struct {
    bool hasValue;
    BareData64 value;
  } avatar;
  struct {
    Color items[8];
    uint32_t len;
  } favorites;
} Profile;

#define PROFILE_MAX_SIZE 140

#define PROFILE_SCHEMA_HASH UINT64_C(0xb4c71ea44c561a1c)

typedef struct {
  UserId user;
  uint64_t when;
} LoginEvent;

#define LOGIN_EVENT_SIZE 16

#define LOGIN_EVENT_SCHEMA_HASH UINT64_C(0x98e7798f4c4eab58)

typedef enum : uint8_t {
  EventTag_LoginEvent = 0,
  EventTag_Profile = 1,
} EventTag;

typedef struct {
  EventTag tag;
  union {
    LoginEvent loginEvent;
    Profile profile;
  } value;
} Event;

#define EVENT_MAX_SIZE 141

#define EVENT_SCHEMA_HASH UINT64_C(0xdd088848706b0f72)

[[nodiscard]] BareStatus userIdRead(BareReader *r, UserId *out);
[[nodiscard]] BareStatus userIdWrite(BareWriter *w, const UserId *value);
[[nodiscard]] BareStatus userIdDecode(UserId *out, const uint8_t buf[], size_t len);
[[nodiscard]] BareStatus userIdEncode(const UserId *value, uint8_t buf[], size_t cap, size_t *written);
[[nodiscard]] bool userIdEqual(const UserId *a, const UserId *b);
[[nodiscard]] BareStatus userIdSkip(BareReader *r);
[[nodiscard]] uint64_t userIdSize(const UserId *value);

[[nodiscard]] BareStatus colorRead(BareReader *r, Color *out);
[[nodiscard]] BareStatus colorWrite(BareWriter *w, const Color *value);
[[nodiscard]] BareStatus colorDecode(Color *out, const uint8_t buf[], size_t len);
[[nodiscard]] BareStatus colorEncode(const Color *value, uint8_t buf[], size_t cap, size_t *written);
[[nodiscard]] bool colorEqual(const Color *a, const Color *b);
[[nodiscard]] BareStatus colorSkip(BareReader *r);
[[nodiscard]] uint64_t colorSize(const Color *value);
const char *colorName(Color value);

[[nodiscard]] BareStatus profileRead(BareReader *r, Profile *out);
[[nodiscard]] BareStatus profileWrite(BareWriter *w, const Profile *value);
[[nodiscard]] BareStatus profileDecode(Profile *out, const uint8_t buf[], size_t len);
[[nodiscard]] BareStatus profileEncode(const Profile *value, uint8_t buf[], size_t cap, size_t *written);
[[nodiscard]] bool profileEqual(const Profile *a, const Profile *b);
[[nodiscard]] BareStatus profileSkip(BareReader *r);
[[nodiscard]] uint64_t profileSize(const Profile *value);

[[nodiscard]] BareStatus loginEventRead(BareReader *r, LoginEvent *out);
[[nodiscard]] BareStatus loginEventWrite(BareWriter *w, const LoginEvent *value);
[[nodiscard]] BareStatus loginEventDecode(LoginEvent *out, const uint8_t buf[], size_t len);
[[nodiscard]] BareStatus loginEventEncode(const LoginEvent *value, uint8_t buf[], size_t cap, size_t *written);
[[nodiscard]] bool loginEventEqual(const LoginEvent *a, const LoginEvent *b);
[[nodiscard]] BareStatus loginEventSkip(BareReader *r);
[[nodiscard]] uint64_t loginEventSize(const LoginEvent *value);

[[nodiscard]] BareStatus eventRead(BareReader *r, Event *out);
[[nodiscard]] BareStatus eventWrite(BareWriter *w, const Event *value);
[[nodiscard]] BareStatus eventDecode(Event *out, const uint8_t buf[], size_t len);
[[nodiscard]] BareStatus eventEncode(const Event *value, uint8_t buf[], size_t cap, size_t *written);
[[nodiscard]] bool eventEqual(const Event *a, const Event *b);
[[nodiscard]] BareStatus eventSkip(BareReader *r);
[[nodiscard]] uint64_t eventSize(const Event *value);
