// Generated by barec from showcase.bare, do not edit.
#pragma once

#include "bare.h"

#include <stddef.h>
#include <stdint.h>

#ifndef BARE_STR64_DEFINED
#define BARE_STR64_DEFINED
typedef struct {
  char data[64] BARE_NONSTRING;
  uint32_t len;
} BareStr64;
#define BARE_STR64(lit) ((BareStr64){.data = "" lit, .len = sizeof(lit) - 1})
#endif

#ifndef BARE_DATA64_DEFINED
#define BARE_DATA64_DEFINED
typedef struct {
  uint8_t data[64];
  uint32_t len;
} BareData64;
#endif

typedef uint64_t UserId;

#define USER_ID_SIZE 8

typedef enum : uint8_t {
  Color_Red = 0,
  Color_Green = 1,
  Color_Blue = 10,
} Color;

#define COLOR_SIZE 1

typedef struct {
  BareStr64 displayName;
  struct {
    bool hasValue;
    BareData64 value;
  } avatar;
  struct {
    Color items[8];
    uint32_t len;
  } favorites;
} Profile;

#define PROFILE_MAX_SIZE 140

typedef struct {
  UserId user;
  uint64_t when;
} LoginEvent;

#define LOGIN_EVENT_SIZE 16

typedef enum : uint8_t {
  EventTag_LoginEvent = 0,
  EventTag_Profile = 1,
} EventTag;

typedef struct {
  EventTag tag;
  union {
    LoginEvent loginEvent;
    Profile profile;
  } value;
} Event;

#define EVENT_MAX_SIZE 141

[[nodiscard]] BareStatus userIdRead(BareReader *r, UserId *out);
[[nodiscard]] BareStatus userIdWrite(BareWriter *w, const UserId *value);
[[nodiscard]] BareStatus userIdDecode(UserId *out, const uint8_t buf[], size_t len);
[[nodiscard]] BareStatus userIdEncode(const UserId *value, uint8_t buf[], size_t cap, size_t *written);

[[nodiscard]] BareStatus colorRead(BareReader *r, Color *out);
[[nodiscard]] BareStatus colorWrite(BareWriter *w, const Color *value);
[[nodiscard]] BareStatus colorDecode(Color *out, const uint8_t buf[], size_t len);
[[nodiscard]] BareStatus colorEncode(const Color *value, uint8_t buf[], size_t cap, size_t *written);

[[nodiscard]] BareStatus profileRead(BareReader *r, Profile *out);
[[nodiscard]] BareStatus profileWrite(BareWriter *w, const Profile *value);
[[nodiscard]] BareStatus profileDecode(Profile *out, const uint8_t buf[], size_t len);
[[nodiscard]] BareStatus profileEncode(const Profile *value, uint8_t buf[], size_t cap, size_t *written);

[[nodiscard]] BareStatus loginEventRead(BareReader *r, LoginEvent *out);
[[nodiscard]] BareStatus loginEventWrite(BareWriter *w, const LoginEvent *value);
[[nodiscard]] BareStatus loginEventDecode(LoginEvent *out, const uint8_t buf[], size_t len);
[[nodiscard]] BareStatus loginEventEncode(const LoginEvent *value, uint8_t buf[], size_t cap, size_t *written);

[[nodiscard]] BareStatus eventRead(BareReader *r, Event *out);
[[nodiscard]] BareStatus eventWrite(BareWriter *w, const Event *value);
[[nodiscard]] BareStatus eventDecode(Event *out, const uint8_t buf[], size_t len);
[[nodiscard]] BareStatus eventEncode(const Event *value, uint8_t buf[], size_t cap, size_t *written);
