// Generated by barec from showcase.bare, do not edit.
#pragma once

#include "bare.h"

#include <stddef.h>
#include <stdint.h>

#ifndef BARE_STR128_DEFINED
#define BARE_STR128_DEFINED
typedef struct {
  char data[128] BARE_NONSTRING;
  uint32_t len;
} BareStr128;
#define BARE_STR128(lit) ((BareStr128){.data = "" lit, .len = sizeof(lit) - 1})
#endif

#ifndef BARE_DATA16_DEFINED
#define BARE_DATA16_DEFINED
typedef struct {
  uint8_t data[16];
  uint32_t len;
} BareData16;
#endif

typedef uint64_t UserId;

#define USER_ID_SIZE 8

typedef enum : uint8_t {
  Color_RED = 0,
  Color_GREEN = 1,
  Color_BLUE = 10,
} Color;

#define COLOR_SIZE 1

typedef struct {
  BareStr128 display_name;
  struct {
    bool has_value;
    BareData16 value;
  } avatar;
  struct {
    Color items[4];
    uint32_t len;
  } favorites;
} Profile;

#define PROFILE_MAX_SIZE 153

typedef struct {
  UserId user;
  uint64_t when;
} LoginEvent;

#define LOGIN_EVENT_SIZE 16

typedef enum : uint8_t {
  EventTag_LOGIN_EVENT = 0,
  EventTag_PROFILE = 1,
} EventTag;

typedef struct {
  EventTag tag;
  union {
    LoginEvent login_event;
    Profile profile;
  } value;
} Event;

#define EVENT_MAX_SIZE 154

[[nodiscard]] BareStatus user_id_read(BareReader *r, UserId *out);
[[nodiscard]] BareStatus user_id_write(BareWriter *w, const UserId *value);
[[nodiscard]] BareStatus user_id_decode(UserId *out, const uint8_t buf[], size_t len);
[[nodiscard]] BareStatus user_id_encode(const UserId *value, uint8_t buf[], size_t cap, size_t *written);
[[nodiscard]] bool user_id_equal(const UserId *a, const UserId *b);

[[nodiscard]] BareStatus color_read(BareReader *r, Color *out);
[[nodiscard]] BareStatus color_write(BareWriter *w, const Color *value);
[[nodiscard]] BareStatus color_decode(Color *out, const uint8_t buf[], size_t len);
[[nodiscard]] BareStatus color_encode(const Color *value, uint8_t buf[], size_t cap, size_t *written);
[[nodiscard]] bool color_equal(const Color *a, const Color *b);
const char *color_name(Color value);

[[nodiscard]] BareStatus profile_read(BareReader *r, Profile *out);
[[nodiscard]] BareStatus profile_write(BareWriter *w, const Profile *value);
[[nodiscard]] BareStatus profile_decode(Profile *out, const uint8_t buf[], size_t len);
[[nodiscard]] BareStatus profile_encode(const Profile *value, uint8_t buf[], size_t cap, size_t *written);
[[nodiscard]] bool profile_equal(const Profile *a, const Profile *b);

[[nodiscard]] BareStatus login_event_read(BareReader *r, LoginEvent *out);
[[nodiscard]] BareStatus login_event_write(BareWriter *w, const LoginEvent *value);
[[nodiscard]] BareStatus login_event_decode(LoginEvent *out, const uint8_t buf[], size_t len);
[[nodiscard]] BareStatus login_event_encode(const LoginEvent *value, uint8_t buf[], size_t cap, size_t *written);
[[nodiscard]] bool login_event_equal(const LoginEvent *a, const LoginEvent *b);

[[nodiscard]] BareStatus event_read(BareReader *r, Event *out);
[[nodiscard]] BareStatus event_write(BareWriter *w, const Event *value);
[[nodiscard]] BareStatus event_decode(Event *out, const uint8_t buf[], size_t len);
[[nodiscard]] BareStatus event_encode(const Event *value, uint8_t buf[], size_t cap, size_t *written);
[[nodiscard]] bool event_equal(const Event *a, const Event *b);
