// Generated by barec from showcase.bare, do not edit.
#pragma once

#include "bare.h"

#include <stddef.h>
#include <stdint.h>

#ifndef BARE_STR64_DEFINED
#define BARE_STR64_DEFINED
typedef struct {
  char data[64] BARE_NONSTRING;
  uint32_t len;
} BareStr64;
#define BARE_STR64(lit) ((BareStr64){.data = "" lit, .len = sizeof(lit) - 1})
#endif

#ifndef BARE_DATA64_DEFINED
#define BARE_DATA64_DEFINED
typedef struct {
  uint8_t data[64];
  uint32_t len;
} BareData64;
#endif

typedef uint64_t user_id_t;

#define USER_ID_SIZE 8

#define USER_ID_SCHEMA_HASH UINT64_C(0x0f25b8a696d73eea)

typedef enum : uint8_t {
  COLOR_RED = 0,
  COLOR_GREEN = 1,
  COLOR_BLUE = 10,
} color_t;

#define COLOR_SIZE 1

#define COLOR_SCHEMA_HASH UINT64_C(0xa4d398d4719edb87)

typedef struct {
  BareStr64 display_name;
  struct {
    bool has_value;
    BareData64 value;
  } avatar;
  struct {
    color_t items[8];
    uint32_t len;
  } favorites;
} profile_t;

#define PROFILE_MAX_SIZE 140

#define PROFILE_SCHEMA_HASH UINT64_C(0xb4c71ea44c561a1c)

typedef struct {
  user_id_t user;
  uint64_t when;
} login_event_t;

#define LOGIN_EVENT_SIZE 16

#define LOGIN_EVENT_SCHEMA_HASH UINT64_C(0x98e7798f4c4eab58)

typedef enum : uint8_t {
  EVENT_TAG_LOGIN_EVENT = 0,
  EVENT_TAG_PROFILE = 1,
} event_tag_t;

typedef struct {
  event_tag_t tag;
  union {
    login_event_t login_event;
    profile_t profile;
  } value;
} event_t;

#define EVENT_MAX_SIZE 141

#define EVENT_SCHEMA_HASH UINT64_C(0xdd088848706b0f72)

[[nodiscard]] BareStatus user_id_read(BareReader *r, user_id_t *out);
[[nodiscard]] BareStatus user_id_write(BareWriter *w, const user_id_t *value);
[[nodiscard]] BareStatus user_id_decode(user_id_t *out, const uint8_t buf[], size_t len);
[[nodiscard]] BareStatus user_id_encode(const user_id_t *value, uint8_t buf[], size_t cap, size_t *written);
[[nodiscard]] bool user_id_equal(const user_id_t *a, const user_id_t *b);
[[nodiscard]] BareStatus user_id_skip(BareReader *r);

[[nodiscard]] BareStatus color_read(BareReader *r, color_t *out);
[[nodiscard]] BareStatus color_write(BareWriter *w, const color_t *value);
[[nodiscard]] BareStatus color_decode(color_t *out, const uint8_t buf[], size_t len);
[[nodiscard]] BareStatus color_encode(const color_t *value, uint8_t buf[], size_t cap, size_t *written);
[[nodiscard]] bool color_equal(const color_t *a, const color_t *b);
[[nodiscard]] BareStatus color_skip(BareReader *r);
const char *color_name(color_t value);

[[nodiscard]] BareStatus profile_read(BareReader *r, profile_t *out);
[[nodiscard]] BareStatus profile_write(BareWriter *w, const profile_t *value);
[[nodiscard]] BareStatus profile_decode(profile_t *out, const uint8_t buf[], size_t len);
[[nodiscard]] BareStatus profile_encode(const profile_t *value, uint8_t buf[], size_t cap, size_t *written);
[[nodiscard]] bool profile_equal(const profile_t *a, const profile_t *b);
[[nodiscard]] BareStatus profile_skip(BareReader *r);

[[nodiscard]] BareStatus login_event_read(BareReader *r, login_event_t *out);
[[nodiscard]] BareStatus login_event_write(BareWriter *w, const login_event_t *value);
[[nodiscard]] BareStatus login_event_decode(login_event_t *out, const uint8_t buf[], size_t len);
[[nodiscard]] BareStatus login_event_encode(const login_event_t *value, uint8_t buf[], size_t cap, size_t *written);
[[nodiscard]] bool login_event_equal(const login_event_t *a, const login_event_t *b);
[[nodiscard]] BareStatus login_event_skip(BareReader *r);

[[nodiscard]] BareStatus event_read(BareReader *r, event_t *out);
[[nodiscard]] BareStatus event_write(BareWriter *w, const event_t *value);
[[nodiscard]] BareStatus event_decode(event_t *out, const uint8_t buf[], size_t len);
[[nodiscard]] BareStatus event_encode(const event_t *value, uint8_t buf[], size_t cap, size_t *written);
[[nodiscard]] bool event_equal(const event_t *a, const event_t *b);
[[nodiscard]] BareStatus event_skip(BareReader *r);
