// Generated by barec from showcase.bare, do not edit.
#pragma once

#include "bare.h"

#include <stddef.h>
#include <stdint.h>

#ifndef BARE_STR64_DEFINED
#define BARE_STR64_DEFINED
typedef struct {
  char data[64] BARE_NONSTRING;
  uint32_t len;
} BareStr64;
#define BARE_STR64(lit) ((BareStr64){.data = "" lit, .len = sizeof(lit) - 1})
#endif

#ifndef BARE_DATA64_DEFINED
#define BARE_DATA64_DEFINED
typedef struct {
  uint8_t data[64];
  uint32_t len;
} BareData64;
#endif

typedef uint64_t AcmeUserId;

typedef enum : uint8_t {
  ACME_RED = 0,
  ACME_GREEN = 1,
  ACME_BLUE = 10,
} AcmeColor;

typedef struct {
  BareStr64 display_name;
  struct {
    bool has_value;
    BareData64 value;
  } avatar;
  struct {
    AcmeColor items[8];
    uint32_t len;
  } favorites;
} AcmeProfile;

typedef struct {
  AcmeUserId user;
  uint64_t when;
} AcmeLoginEvent;

typedef enum : uint8_t {
  ACME_LOGIN_EVENT = 0,
  ACME_PROFILE = 1,
} AcmeEventTag;

typedef struct {
  AcmeEventTag tag;
  union {
    AcmeLoginEvent login_event;
    AcmeProfile profile;
  } value;
} AcmeEvent;

[[nodiscard]] BareStatus acme_user_id_read(BareReader *r, AcmeUserId *out);
[[nodiscard]] BareStatus acme_user_id_write(BareWriter *w, const AcmeUserId *value);
[[nodiscard]] BareStatus acme_user_id_decode(AcmeUserId *out, const uint8_t buf[], size_t len);
[[nodiscard]] BareStatus acme_user_id_encode(const AcmeUserId *value, uint8_t buf[], size_t cap, size_t *written);

[[nodiscard]] BareStatus acme_color_read(BareReader *r, AcmeColor *out);
[[nodiscard]] BareStatus acme_color_write(BareWriter *w, const AcmeColor *value);
[[nodiscard]] BareStatus acme_color_decode(AcmeColor *out, const uint8_t buf[], size_t len);
[[nodiscard]] BareStatus acme_color_encode(const AcmeColor *value, uint8_t buf[], size_t cap, size_t *written);

[[nodiscard]] BareStatus acme_profile_read(BareReader *r, AcmeProfile *out);
[[nodiscard]] BareStatus acme_profile_write(BareWriter *w, const AcmeProfile *value);
[[nodiscard]] BareStatus acme_profile_decode(AcmeProfile *out, const uint8_t buf[], size_t len);
[[nodiscard]] BareStatus acme_profile_encode(const AcmeProfile *value, uint8_t buf[], size_t cap, size_t *written);

[[nodiscard]] BareStatus acme_login_event_read(BareReader *r, AcmeLoginEvent *out);
[[nodiscard]] BareStatus acme_login_event_write(BareWriter *w, const AcmeLoginEvent *value);
[[nodiscard]] BareStatus acme_login_event_decode(AcmeLoginEvent *out, const uint8_t buf[], size_t len);
[[nodiscard]] BareStatus acme_login_event_encode(const AcmeLoginEvent *value, uint8_t buf[], size_t cap, size_t *written);

[[nodiscard]] BareStatus acme_event_read(BareReader *r, AcmeEvent *out);
[[nodiscard]] BareStatus acme_event_write(BareWriter *w, const AcmeEvent *value);
[[nodiscard]] BareStatus acme_event_decode(AcmeEvent *out, const uint8_t buf[], size_t len);
[[nodiscard]] BareStatus acme_event_encode(const AcmeEvent *value, uint8_t buf[], size_t cap, size_t *written);
