// Generated by barec 0.3.0 from showcase.bare, do not edit.
#pragma once

#include "bare.h"

#include <stddef.h>
#include <stdint.h>

#ifndef BARE_STR64_DEFINED
#define BARE_STR64_DEFINED
typedef struct {
  char data[64] BARE_NONSTRING;
  uint32_t len;
} BareStr64;
#define BARE_STR64(lit) ((BareStr64){.data = "" lit, .len = (sizeof(struct { int bare_string_literal_longer_than_capacity : sizeof(lit) - 1 <= 64 ? 1 : -1; }) * 0) + sizeof(lit) - 1})
#endif

#ifndef BARE_DATA64_DEFINED
#define BARE_DATA64_DEFINED
typedef struct {
  uint8_t data[64];
  uint32_t len;
} BareData64;
#endif

typedef uint64_t AcmeUserId;

#define ACME_USER_ID_SIZE 8

#define ACME_USER_ID_SCHEMA_HASH UINT64_C(0x0f25b8a696d73eea)

typedef enum : uint8_t {
  ACME_RED = 0,
  ACME_GREEN = 1,
  ACME_BLUE = 10,
} AcmeColor;

#define ACME_COLOR_SIZE 1

#define ACME_COLOR_SCHEMA_HASH UINT64_C(0xa4d398d4719edb87)

typedef struct {
  BareStr64 display_name;
  struct {
    bool has_value;
    BareData64 value;
  } avatar;
  struct {
    AcmeColor items[8];
    uint32_t len;
  } favorites;
} AcmeProfile;

#define ACME_PROFILE_MAX_SIZE 140

#define ACME_PROFILE_SCHEMA_HASH UINT64_C(0xb4c71ea44c561a1c)

typedef struct {
  AcmeUserId user;
  uint64_t when;
} AcmeLoginEvent;

#define ACME_LOGIN_EVENT_SIZE 16

#define ACME_LOGIN_EVENT_SCHEMA_HASH UINT64_C(0x98e7798f4c4eab58)

typedef enum : uint8_t {
  ACME_LOGIN_EVENT = 0,
  ACME_PROFILE = 1,
} AcmeEventTag;

typedef struct {
  AcmeEventTag tag;
  union {
    AcmeLoginEvent login_event;
    AcmeProfile profile;
  } value;
} AcmeEvent;

#define ACME_EVENT_MAX_SIZE 141

#define ACME_EVENT_SCHEMA_HASH UINT64_C(0xdd088848706b0f72)

[[nodiscard]] BareStatus acme_user_id_read(BareReader *r, AcmeUserId *out);
[[nodiscard]] BareStatus acme_user_id_write(BareWriter *w, const AcmeUserId *value);
[[nodiscard]] BareStatus acme_user_id_decode(AcmeUserId *out, const uint8_t buf[], size_t len);
[[nodiscard]] BareStatus acme_user_id_encode(const AcmeUserId *value, uint8_t buf[], size_t cap, size_t *written);
[[nodiscard]] bool acme_user_id_equal(const AcmeUserId *a, const AcmeUserId *b);
[[nodiscard]] BareStatus acme_user_id_skip(BareReader *r);
[[nodiscard]] uint64_t acme_user_id_size(const AcmeUserId *value);

[[nodiscard]] BareStatus acme_color_read(BareReader *r, AcmeColor *out);
[[nodiscard]] BareStatus acme_color_write(BareWriter *w, const AcmeColor *value);
[[nodiscard]] BareStatus acme_color_decode(AcmeColor *out, const uint8_t buf[], size_t len);
[[nodiscard]] BareStatus acme_color_encode(const AcmeColor *value, uint8_t buf[], size_t cap, size_t *written);
[[nodiscard]] bool acme_color_equal(const AcmeColor *a, const AcmeColor *b);
[[nodiscard]] BareStatus acme_color_skip(BareReader *r);
[[nodiscard]] uint64_t acme_color_size(const AcmeColor *value);
const char *acme_color_name(AcmeColor value);

[[nodiscard]] BareStatus acme_profile_read(BareReader *r, AcmeProfile *out);
[[nodiscard]] BareStatus acme_profile_write(BareWriter *w, const AcmeProfile *value);
[[nodiscard]] BareStatus acme_profile_decode(AcmeProfile *out, const uint8_t buf[], size_t len);
[[nodiscard]] BareStatus acme_profile_encode(const AcmeProfile *value, uint8_t buf[], size_t cap, size_t *written);
[[nodiscard]] bool acme_profile_equal(const AcmeProfile *a, const AcmeProfile *b);
[[nodiscard]] BareStatus acme_profile_skip(BareReader *r);
[[nodiscard]] uint64_t acme_profile_size(const AcmeProfile *value);

[[nodiscard]] BareStatus acme_login_event_read(BareReader *r, AcmeLoginEvent *out);
[[nodiscard]] BareStatus acme_login_event_write(BareWriter *w, const AcmeLoginEvent *value);
[[nodiscard]] BareStatus acme_login_event_decode(AcmeLoginEvent *out, const uint8_t buf[], size_t len);
[[nodiscard]] BareStatus acme_login_event_encode(const AcmeLoginEvent *value, uint8_t buf[], size_t cap, size_t *written);
[[nodiscard]] bool acme_login_event_equal(const AcmeLoginEvent *a, const AcmeLoginEvent *b);
[[nodiscard]] BareStatus acme_login_event_skip(BareReader *r);
[[nodiscard]] uint64_t acme_login_event_size(const AcmeLoginEvent *value);

[[nodiscard]] BareStatus acme_event_read(BareReader *r, AcmeEvent *out);
[[nodiscard]] BareStatus acme_event_write(BareWriter *w, const AcmeEvent *value);
[[nodiscard]] BareStatus acme_event_decode(AcmeEvent *out, const uint8_t buf[], size_t len);
[[nodiscard]] BareStatus acme_event_encode(const AcmeEvent *value, uint8_t buf[], size_t cap, size_t *written);
[[nodiscard]] bool acme_event_equal(const AcmeEvent *a, const AcmeEvent *b);
[[nodiscard]] BareStatus acme_event_skip(BareReader *r);
[[nodiscard]] uint64_t acme_event_size(const AcmeEvent *value);
